### PR TITLE
Fix issue #85 that Subscription.isUnsubscribed returns a wrong value

### LINKED ISSUE #85: Auto unsubscribe bug
The following should print `true` and `true` (does in Java for apply).

``` scala
object Main {
  def main(args: Array[String]): Unit = {
    val xs = Observable.create[Nothing](o => {
      o.onCompleted()
      Subscription{ println("...") }
    })
    val s = xs.subscribe()
    println(s.isUnsubscribed)
    val ys = Observable[Nothing](o => {
      o.onCompleted()
    })
    val z = ys.subscribe()
    println(z.isUnsubscribed)
    readLine()
  }
}
```

### PR DESCRIPTION
**Pull request by zsxwing**
Fix #85

### CODE REVIEW

File: src/main/scala/rx/lang/scala/Subscription.scala [hunk 1]
```diff
@@ -41,23 +41,22 @@ import java.util.concurrent.atomic.AtomicBoolean
  */
 trait Subscription {
 
-  private [scala] val unsubscribed = new AtomicBoolean(false)
-  private [scala] val asJavaSubscription: rx.Subscription = new rx.Subscription {
-    override def unsubscribe() { unsubscribed.compareAndSet(false, true) }
-    override def isUnsubscribed(): Boolean = { unsubscribed.get() }
-  }
-
+  private[scala] val asJavaSubscription: rx.Subscription = rx.subscriptions.BooleanSubscription.create()
```
Comment (samuelgruetter) [inline src/main/scala/rx/lang/scala/Subscription.scala:44]: I like this change: We're not reimplementing the wheel any more, and we follow the same pattern as Subscriber (default asJava val, which is overridden in apply constructors if needed).

**Comment by samuelgruetter** [comment]
LGTM
